# Generated by Django 4.2.1 on 2023-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('singer', models.TextField()),
                ('tag', models.TextField()),
                ('img', models.ImageField(upload_to='gallary')),
                ('file', models.FileField(upload_to='galleryt')),
            ],
        ),
    ]
